name: njson ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        include:
          - image: erlang:25
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      options: "--entrypoint /bin/bash"
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v2
      - uses: nomasystems/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Inspect rebar3 version
      - name: Rebar version
        run: rebar3 --version

      # PRE Checks
      - name: Checks
        run: rebar3 check

      # Compile
      - name: Compile
        run: rebar3 compile

      # Tests
      - name: Run tests
        run: rebar3 ci_test
      - name: Store test logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: ct-logs
          path: _build/test/logs

      # Publish test report
      - name: Publish Test Report
        uses: nomasystems/action-junit-report@v2
        with:
          report_paths: '_build/test/logs/**/report.xml'
